"""empty message

Revision ID: 641c17b0b920
Revises: e5f41f8e07a6
Create Date: 2018-05-02 21:00:57.508396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '641c17b0b920'
down_revision = 'e5f41f8e07a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'distance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('distance', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    # ### end Alembic commands ###
